version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '20:00'
      timezone: 'Asia/Tokyo'
    reviewers:
      - 'yasudanaoya'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automerge'
    ignore:
      - dependency-name: 'node-sass'
        versions: ['5.x', '6.x']
      - dependency-name: 'sass-loader'
        versions: ['11.x', '12.x']
