name: Assign PR Author as Assignee

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v0.1.0
        with:
          assignees: ${{ github.actor }}
          reviewers: yasudanaoya
